
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import ttk
import pandas as pd
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage



window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

entry_1 = ttk.Combobox(
    window,
    values=['a','b'],
    state="readonly"  # Faz com que apenas os valores da lista possam ser selecionados
)
entry_1.place(x=82.0, y=82.0, width=133.0, height=22.0)


entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=317.0,
    y=82.0,
    width=133.0,
    height=22.0
)


entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=552.0,
    y=82.0,
    width=133.0,
    height=22.0
)


entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=26.0,
    y=152.0,
    width=746.0,
    height=416.0
)

canvas.create_text(
    82.0,
    49.0,
    anchor="nw",
    text="TICKER",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    565.0,
    49.0,
    anchor="nw",
    text="STRIKE\n",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    330.0,
    49.0,
    anchor="nw",
    text="VENCIMENTO\n",
    fill="#000000",
    font=("Inter", 14 * -1)
)
window.resizable(False, False)

window.mainloop()
